accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.LoginView.as_view(), name='login'),
    
    path('signup/', views.signup, name='signup'),
    
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('working/', views.working, name='working'),
    path('send_capture/', views.send_capture(), name='send_capture'),
    path('finish_task/', views.finish_task, name='finish_task'),
    path('data_list/', views.DataList.as_view(), name='data_list'),
]

face_detection_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('accounts.urls')),
    path('', include('app.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

app/models.py
from django.db import models
from django.contrib.auth.models import User

class Activity(models.Model):

    user = models.ForeignKey(
        to=User,
        verbose_name='User',
        on_delete=models.CASCADE
    )

    start_time = models.DateTimeField(
        verbose_name='start_time'
    )

    finish_time = models.DateTimeField(
        verbose_name='finish_time'
    )

    not_working_time = models.IntegerField(
        verbose_name='not_working_time'
    )

    working_time = models.IntegerField(
        verbose_name='working_time'
    )


    class Meta:
        verbose_name_plural='Activity'
    

class ActivityDetail(models.Model):

    activity = models.ForeignKey(
        to=Activity,
        verbose_name='Activity',
        on_delete=models.CASCADE
    )

    rest_start_time = models.DateField(
        verbose_name='rest_start_time',
    )

    rest_finish_time = models.DateField(
        verbose_name='rest_finish_time'
    )

    class Meta:
        verbose_name_plural='ActivityDetails'

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm 


class LoginForm(AuthenticationForm):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label   

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from .forms import LoginForm
from django.http import HttpResponse, request
from django.contrib.auth import login, authenticate


class Login(LoginView):
    """ Login Page """

    form_class = LoginForm
    template_name = 'login.html'


"""

def signup(request):
    return render(request, 'registration/signup.html')
"""

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('app:index')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})



        





class Logout(LoginRequiredMixin, LogoutView):
    """ Logout Page """

    template_name = 'login.html'

app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.http import StreamingHttpResponse
from django.urls import reverse_lazy

from .models import Activity

from face_detection_management.settings.base import FACE_CASCADE_PATH

import datetime, time

import sys
import cv2

import os

class IndexView(generic.TemplateView):

    template_name = 'index.html'

@login_required
def working(request):
    global not_working_time, start_time
    not_working_time = 0
    start_time = datetime.datetime.now()
    context = {
        'start_time' : start_time,
    }
    return render(request, 'working.html', context)

def capture():
    global not_working_time

    cap = cv2.VideoCapture(0, cv2.CAP_DSHOW)

    if cap.isOpened() is False:
        print("can not open camera")
        sys.exit()

    cascade = cv2.CascadeClassifier(FACE_CASCADE_PATH)

    now = time.time()
    
    while True:
        prev = now
        now = time.time()
        # VideoCaptureから1フレーム読み込む
        ret, frame = cap.read()

        # そのままの大きさだと処理速度がきついのでリサイズ
        frame = cv2.resize(frame, (int(frame.shape[1]*0.7), int(frame.shape[0]*0.7)))

        # 処理速度を高めるために画像をグレースケールに変換したものを用意
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        # 顔検出
        facerect = cascade.detectMultiScale(
            gray,
            scaleFactor=1.11,
            minNeighbors=3,
            minSize=(100, 100)
        )

        if len(facerect) != 0:
            for x, y, w, h in facerect:
                # 顔の部分
                face_gray = gray[y: y + h, x: x + w]

                # 顔検出した部分に枠を描画
                cv2.rectangle(
                    frame,
                    (x, y),
                    (x + w, y + h),
                    (255, 255, 255),
                    thickness=2
                )
        else:
            not_working_time += (now - prev)
        
        # フレーム画像をバイナリに変換
        ret, jpeg = cv2.imencode('.jpg', frame)
        byte_frame = jpeg.tobytes()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + byte_frame + b'\r\n\r\n')

    # キャプチャをリリースして、ウィンドウをすべて閉じる
    cap.release()

def send_capture():
    return lambda _: StreamingHttpResponse(capture(), content_type='multipart/x-mixed-replace; boundary=frame')
    
@login_required
def finish_task(request):
    global start_time, not_working_time

    try:
        not_working_time = int(not_working_time)
        finish_time = datetime.datetime.now()
        time_diff = (finish_time - start_time)
        time_diff = time_diff.seconds
        working_time = time_diff - not_working_time


        activity = Activity.objects.create(
            user = request.user,
            start_time = start_time,
            finish_time = finish_time,
            not_working_time = not_working_time,
            working_time = working_time
        )

        working_hours = working_time // 3600
        working_time %= 3600
        working_minutes = working_time // 60
        working_seconds = working_time % 60

        not_working_hours = int(not_working_time // 3600)
        not_working_time %= 3600
        not_working_minutes = int(not_working_time // 60)
        not_working_seconds = int(not_working_time % 60)

        context = {'working_hours' : working_hours, 'working_minutes' : working_minutes, 'working_seconds' : working_seconds, 'start_time' : start_time, 'finish_time' : finish_time, 'not_working_hours' : not_working_hours, 'not_working_minutes' : not_working_minutes, 'not_working_seconds' : not_working_seconds}

        del start_time

    except:
        return redirect('app:index')

    

    return render(request, 'finish_task.html', context)

class DataList(LoginRequiredMixin, generic.ListView):

    template_name = 'data_list.html'
    context_object_name = 'activities'
    
    def get_queryset(self):
        activities = Activity.objects.filter(user=self.request.user).order_by('-start_time')
        return activities

templates/base.html
<!-- friends_management/templates/base.html -->
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>face detection management</title>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/dracula.min.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<style>
    body {
        background-color: rgb(105, 100, 95);
    }
    
</style>



<body>


    


    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'app:index' %}">Face Detection Management</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  {% if user.is_authenticated %}
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app:index' %}">Activity</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app:data_list' %}">データをみる</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-danger" href="{% url 'accounts:logout' %}">サインアウト</a>
      </li>

    </ul>
  </div>

  <!--ログインしていないとき-->
  {% else %}
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}">ログイン・新規登録</a>
      </li>
    </ul>
  </div>
  {% endif %}
      </nav>




    {% block content %}
    {% endblock %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

templates/data_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<p></p>

<script>
    var times = new Array();
    var areas = [
    {% for area in activities %}
    {{area.working_time}},
    {% endfor %}
    ];
    console.log(areas);   
    areas.reverse();   

</script>

<script>
  for(var i = 0; i < areas.length; i++) {
    times.push(areas[i] / 60);
    console.log(times[i]);   
  }
</script>

<script>
  for(var i = 0; i < areas.length; i++) {
    areas[i] /= 60;
    areas[i] = areas[i] | 0;
  }
</script>




<script>
     var days = [
    {% for area in activities %}
    "",
    {% endfor %}
    ];

    console.log(days);   
    days.reverse();   

</script>

<div class = "container-fluid p-5">
    <div class = "card">
    <p></p>
    <div class="container">
      <div>
        <canvas id="myChart"></canvas>
      </div>
    </div>

<p></p>

  <div class = "container-fluid p-5">
    <table border = "1" class = "my-table">
        <tr>
            <th>開始時刻</th>
            <th>終了時刻</th>
            <th>作業時間(分)</th>
            <th>作業時間(秒)</th>
        </tr>
        {% for activity in activities %}
        <tr>
            <td>{{ activity.start_time|date:"Y/n/j H:i:s" }}</td>
            <td>{{ activity.finish_time|date:"Y/n/j H:i:s" }}</td>
    
            <script>
              var minute = {{ activity.working_time}};
              minute /= 60;
              minute  = minute | 0;
              document.write(`<td>${minute}</td>`);

              var second = {{ activity.working_time }};
              second %= 60;
              second = second | 0;
              document.write(`<td>${second}</td>`);
            </script>
        
        </tr>
        {% endfor %}
    </table>
        </div>
    </div>

</div>

<div class = "hoge">
</div>

<script>


</script>



<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>


<script>
    var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
  type: 'bar',
  data: {
    labels: days,
    datasets: [{
      label: "作業時間(分)",
      data: times,
      backgroundColor: "rgba(255,0,0,0.4)"
    }]
  }
});

</script>

<style>
  .my-table {
    text-align: center;
  }

</style>

{% endblock %}

templates/finish_task.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<p></p>

<div class = "container-fluid">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">今回の作業時間は{{ working_hours }}時間{{ working_minutes }}分{{ working_seconds }}秒でした</h5>

            <p>開始時刻 : {{ start_time|date:"Y/n/j H:i:s" }}</p>
            <p>終了時刻 : {{ finish_time|date:"Y/n/j H:i:s" }}</p>
            <p>休憩時間 : {{ not_working_hours }}時間{{ not_working_minutes }}分{{ not_working_seconds }}秒</p>
        </div>
      </div>
</div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<p></p>

<div class = "container-fluid">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">
            <p id = "RealtimeClockArea"></p>
            </h4>



    <a href="{% url 'app:working' %}" class = "btn btn-primary w-100">START</a>
    
    <p></p>
    
          
          <ul>
            <li>STARTで作業を開始</li>
            <li>FINISHで作業終了</li>
            <li>目を離したら休憩になります</li>
          </ul>

         
        </div>
      </div>
</div>

<script>

function set2fig(num) {
   // 桁数が1桁だったら先頭に0を加えて2桁に調整する
   var ret;
   if( num < 10 ) { ret = "0" + num; }
   else { ret = num; }
   return ret;
}
function showClock2() {
   var nowTime = new Date();
   var nowHour = set2fig( nowTime.getHours() );
   var nowMin  = set2fig( nowTime.getMinutes() );
   var nowSec  = set2fig( nowTime.getSeconds() );
   var msg = "現在時刻は、" + nowHour + ":" + nowMin + ":" + nowSec + " です。";
   document.getElementById("RealtimeClockArea").innerHTML = msg;
}
setInterval('showClock2()',1000);

</script>


{% endblock %}

templates/working.html
{% extends 'base.html' %}
{% load static %}
{% block content %}




<p></p>
<div class = "container-fluid">
    <div class="card">
        <div class="card-body">
            <h3>作業開始時刻: {{ start_time }}</h3>

<p></p>
<div>
    <div id="image_area">
        <div class = "container-fluid my-btn">
        <img src="{% url 'app:send_capture' %}" class = "my-face"/>
        <p></p>
        <a href="{% url 'app:finish_task' %}" class = "btn btn-danger w-25">FINISH</a>
        </div>
    </div>
   
</div>

         
        </div>
      </div>
</div>

<style>
    .my-face {
        width:100%;
        height: 320px;
        object-fit: contain;
    }

    .my-btn {
        text-align: center;
    }
</style>
{% endblock %}